apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "datark.backend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datark.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ include "datark.host" . | quote }}
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
  rules:
    - host: {{ include "datark.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "datark.backend.name" . }}
                port:
                  number: 80
